### ISSUE TITLE
New senders: Servus TV, etc.

### ISSUE THREAD

**Issue by Flexmaen** [fayer3/plugin.video.zappntv#3]
First of all: Thank you for the plugin!

Around 24th September 2019 new senders were added to Zappn: ServusTV, SchauTV, RIC TV and Cineplexx TV.
These are missing in the current release.

**Comment by fayer3** [comment]
Will look into it, probably need to adapt the new api for that. 
I am currently working on updating my joyn addon. When that's done, I will have a look at this.

**Comment by fayer3** [comment]
sorry for the late change.
the new channels are now in version 1.2.4
