### ISSUE TITLE
Kodi API change with v19

### ISSUE THREAD

**Issue by luchmhor** [fayer3/plugin.video.zappntv#5]
after the change to python3 kodi now also has changed the API and disables incompatible plugins. Maybe you could provide a commit / branch for that. See the discussion here at the orf tvthek plugin:

https://github.com/s0faking/plugin.video.orftvthek/issues/96

**Comment by gsantner** [comment]
@luchmhor 
There is a (1) unreleased commit on master which added support for Kodi 19, actually pushed in december before your comment.

@fayer3   
Any plans to release a update containing the change for Kodi 19?

**Comment by fayer3** [comment]
this is actually released already, just forgot to close this issue
use:  plugin.video.zappntv-1.3.4+matrix.1.zip
https://github.com/fayer3/plugin.video.zappntv/releases/tag/v1.3.4

**Comment by fayer3** [comment]
I didn't make a new release version, since it's basically the same version, just ported to kodi 19

**Comment by gsantner** [comment]
I installed the kodinerds repo and Zappn didnt show up for me for some reason. Only getting zip from master worked for me.

**Comment by fayer3** [comment]
yeah, I think it isn't in the kodi 19 kodinerds repo, need to talk to them, to add it.

**Comment by gsantner** [comment]
OK, btw I guess discussion and everything here can be german right? everything you can do with this project is watching/listening to german content.

I also saw lots of error popups when I start the zappn addon, though live stream playback works.

**Comment by fayer3** [comment]
Can be German but, I use English, because its an English platform.
regarding the errors, it would probably best to start a new issue so we don't spam luchmhor with notifications
