### ISSUE TITLE
Addon broken after Updates

### ISSUE THREAD

**Issue by cstrassmair** [fayer3/plugin.video.zappntv#7]
Iam using this Addon on Kodi 19.3 on multiple Android TV devices and on Android Phone.

After i updated all addons and this addon itself, its broken.

A downgrade doesnt help after that happened.

**Comment by fayer3** [comment]
?
shouldn't break other addons
logs?

**Comment by gsantner** [comment]
since updating recently, Zappn on Kodi doesn't work anymore at all here. It worked flawless before, on Kodi 19.

**Comment by fayer3** [comment]
post your log then
latest update shouldn't have broken anything

**Comment by Schaussi** [comment]
I am also experiencing issues since today.

Log:

> 2021-12-20 19:00:20.190 T:3415    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'ModuleNotFoundError'>
>                                                    Error Contents: No module named 'backports'
>                                                    Traceback (most recent call last):
>                                                      File "/storage/.kodi/addons/plugin.video.zappntv/main.py", line 4, in <module>
>                                                        from resources.lib import plugin
>                                                      File "/storage/.kodi/addons/plugin.video.zappntv/resources/lib/plugin.py", line 19, in <module>
>                                                        import tzlocal
>                                                      File "/storage/.kodi/addons/script.module.tzlocal/lib/tzlocal/__init__.py", line 5, in <module>
>                                                        from tzlocal.unix import get_localzone, reload_localzone
>                                                      File "/storage/.kodi/addons/script.module.tzlocal/lib/tzlocal/unix.py", line 12, in <module>
>                                                        from backports.zoneinfo import ZoneInfo, ZoneInfoNotFoundError
>                                                    ModuleNotFoundError: No module named 'backports'
>                                                    -->End of Python script error report<--
> 
> 2021-12-20 19:00:20.505 T:3415     INFO <general>: Python interpreter stopped
> 2021-12-20 19:00:20.516 T:3413    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.zappntv/
> 2021-12-20 19:00:20.532 T:2995    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.zappntv/) failed

One thing I tried was to reinstall InputStream Helper, with no success.
Addon version is 1.3.5+matrix.1.
Please tell me if you need any more details.
Best regards and thank you for this addon.

**Comment by ad0bert** [comment]
Also stumbbled over the error above seems to have something todo with the Tzlocal dependency see the discussion over there: https://www.kodinerds.net/index.php/Thread/66455-Release-ZAPPN-TV/?pageNo=23

**Comment by cstrassmair** [comment]
Yes thanks thats it! Downgraded tzlocal from v3 to v2 as Workarround and its running

**Comment by fayer3** [comment]
looks to be caused solely by the tzlocal module, nothing I can do to fix a problem with that.
I can look into removing the module with the next version, if it's not too much work.
